name: Sync to Hugging Face hub
on:
  push:
    branches: [main]

  # to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  sync-to-hub:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
          lfs: true
      - name: Remove binary files
        run: |
          git rm --cached assets/images/Guess_the_Character.png assets/images/Talk_to_Character.png assets/images/Recommender_System.png
          git commit -m "Remove binary files"
      - name: Push to hub
        env:
          HF_TOKEN: ${{ secrets.HF_TOKEN }}
        run: git push --force https://iSathyam03:$HF_TOKEN@huggingface.co/spaces/iSathyam03/OtakuOracle main
